### ISSUE TITLE
Multipath

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#274]
Tracking issue for all [Equal Cost Multi-path Routing](https://en.wikipedia.org/wiki/Equal-cost_multi-path_routing) work items.

We wish to support the following multi-path strategies:

- Classic (traceroute and MTR)
  - Set the sequence number in either the src or dest port number
- Paris (see [here](https://github.com/libparistraceroute/libparistraceroute/wiki/Checksum))
  - Use the IPv4 `checksum` field to store the sequence and manipulate the UDP payload to ensure a valid packet 
- Dublin (see [here](https://github.com/insomniacslk/dublin-traceroute))
  - Use the IPv4 `identifier` field to store the sequence number
  - Manipulate the IPv6 `Payload Length` to store the sequence number
  
We wish to support these for IPv4 & IPv6 for both UDP and TCP protocols.

## Current support:

TODO - table

## Tasks

- [ ] Use IP `identifier` for UDP sequence number
- [ ] Mode to increment src/dest port per _round_ for UDP
- [ ] Ability to select classic or `dublin` (and `paris`) modes for UDP?
- [ ] Detect NAT for `dublin` mode
- [ ] Record per-path trace data
- [ ] TUI changes to show split/merged path data
- [ ] Dublin traceroute for IPv6/UDP (see [#272](https://github.com/fujiapple852/trippy/issues/272))

**Comment by crisidev** [comment]
In this tracking issue there is no mention of supporting Paris for IPv6. Is it something planned by any chance?

**Comment by fujiapple852** [comment]
@crisidev I'd certainly like for Trippy to be able to support the Paris ECMP strategy for IPv6/UDP.

I'm struggling to recall the details now but I know that when I initially added IPv6/UDP support to Trippy I hit some [issues](https://github.com/fujiapple852/trippy/issues/35#issuecomment-1135423060) with IPv6/UDP checksum on Linux (may have been related to hardware offloading).

As a reminder: the Paris ECMP strategy works by manipulating the UDP checksum (and payload) to encode the sequence number in the checksum.  In order to do this we need to be able to specify (or manipulate) the IPv6/UDP header.

It might be possible to set `IP_HDRINCL` (or perhaps `IPV6_HDRINCL`?) on the IPv6/UDP raw socket such that the correct checksum could be set, I'd have to try it again to see.  At the time I opened this GH issue I likely believed it was not possible.  Digging into the [libparistraceroute](https://github.com/libparistraceroute/libparistraceroute) src code may also help point at the right solution.

Is using the Paris ECMP strategy for IPv6/UDP something you have experience with?  I'm curious as to your use case for it.

**Comment by crisidev** [comment]
Thanks a lot for the detailed answer. I unfortunately do not have a lot of experience with Paris ECMP for IPv6/UDP. I have a pretty complex IPv6 home network I am currently experimenting using the official Paris traceroute, but I am well versed and love Rust, hence I would like to rewrite my probe code and base it on Trippy. 

I just started scratching the surface of your amazing project, but when I have a little bit of time, I could try to reintroduce this support, after properly understanding how Paris traceroute does it in their library.

**Comment by fujiapple852** [comment]
@crisidev I managed to get it to work :)

Tested in Linux and macOS and seems to work.

Issue #749 and WIP pr in #750

**Comment by crisidev** [comment]
Oh wow, that was fast! I'll try this out today!

**Comment by fujiapple852** [comment]
@crisidev Dublin for IPv6 just merged and will be in 0.10.0 if that's of interest to you.

**Comment by Pruthviraj1223** [comment]
Hello is there any update for Paris and Dublin support for TCP protocol ??? I am really interested into this and also I'm working on something where this will be very helpful

**Comment by fujiapple852** [comment]
@Pruthviraj1223 I'm afraid not.

This is one of the “big ticket” topics I [listed](https://trippy.zulipchat.com/#narrow/stream/436136-general/topic/Trippy.20in.202025.20-.20what's.20next.3F) a few months ago.

What makes this hard is that, for TCP, trippy operates at layer 7 rather than layer 3/4 due to various OS restrictions. I’d need to experiment, but it may not be possible without resorting to sending packets at layer 2 or using TAP/TUN or eBPF. 

Certainly something I’m keep to support, but as it is nontrivial it’ll take time. 

Aside: I’d be interested in hearing what you plan to use this for?

**Comment by Pruthviraj1223** [comment]
Thank you for your response.

Actually I have not dig into the Paris trace route code , but my requirement was to trace the packet from source to destination, with packet loss and latency and discover router/ hop in between. And when a multipath occurs, the main issue is the packet loss and latency , I have not come across a single command or Library which gives me packet loss and latency, especially at multipath.  And the reason to choose TCP protocol is that routers do not generally drop/block TCP packet in comparison to ICMP/UDP. And few servers like facebook.com etc. do not give the response to UDP packets. Please correct me if I am wrong. In order to understand anything wrong.


If you could help me solve this problem by sharing your insights or anything that I'm missing here, it would be great. 

Also I would love to contribute in the future, once i debug and understand, I'll definitely do that.

**Comment by Pruthviraj1223** [comment]
Thank you for your response.

Actually I have not dig into the Paris trace route code , but my requirement was to trace the packet from source to destination, with packet loss and latency and discover router/ hop in between. And when a multipath occurs, the main issue is the packet loss and latency , I have not come across a single command or Library which gives me packet loss and latency, especially at multipath.  And the reason to choose TCP protocol is that routers do not generally drop/block TCP packet in comparison to ICMP/UDP. And few servers like facebook.com etc. do not give the response to UDP packets. Please correct me if I am wrong. In order to understand anything wrong.


If you could help me solve this problem by sharing your insights or anything that I'm missing here, it would be great. 

Also I would love to contribute in the future, once i debug and understand, I'll definitely do that.
