### ISSUE TITLE
Flows

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#776]
Tracking issue for flows.

A flow represents a unique sequence of hosts traversed from the source to the target.  As Trippy runs multiple rounds of tracing and, in most cases*, each round may pass through a different sequence of hosts.  It is therefore useful to be able to isolate individual flows in order to be able to analyse 

Note that this only accounts for flow for outgoing packets, Trippy (and traceroute in general) has no visibility of the path of incoming packets.

* ICMP tracing typically uses the same flow for each round, though it is not guaranteed to do so.  UDP and TCP tracing do not use the same flow for each round unless the Dublin or Paris tracing strategy are used.

- [x] https://github.com/fujiapple852/trippy/issues/768
- [x] https://github.com/fujiapple852/trippy/issues/760
- [x] https://github.com/fujiapple852/trippy/issues/770
- [x] https://github.com/fujiapple852/trippy/issues/582
- [x] #777
